version: '3.7'
services:

  demo-db:
    container_name: demo-db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - $HOME/demo/db/:/var/lib/postgresql/data